### ISSUE TITLE
TTT2 

### ISSUE THREAD

**Issue by lukazuvic** [TillMacher/TaxonTableTools#11]
Hi Till, 
sorry to bother you, I know you're busy. I just wanted to ask you if you could give me an approximate date when TTT2 will be released, because I have some deadlines and I'm wondering if it's better to wait for TTT2 to be released or to work with TTT1. And also will TTT1 be deactivated after the release of TTT2?

BR,
Luka

**Comment by TillMacher** [comment]
Hi Luka,

I am currently planning to release TTT2.0 in December. Probably it will not include all previous functions, but I will add them over the next couple of months. I will let you know when it is released!

cheers
Till
