### ISSUE TITLE
TaXon tables get corrupt when plotting Taxonomic resolution / richness

### ISSUE THREAD

**Issue by OndroV** [TillMacher/TaxonTableTools#2]
Hello! My TaXon tables get consumed after running "Taxonomic resolution" or "Taxonomic richness". 
Their file size becomes 0 KB and Excel can't open them, "because the file format or file extension is not vaild." The plots are saved as expected, but I need to backup the TaXon table before running either of the two commands.
Other functions work fine. First I thought that it's a consequence of the warning about non-"binomial taxonomy" in my input table, but I fixed the taxonomy and the problem persists.
I set up TTT on Windows 10 last week.

**Comment by TillMacher** [comment]
Thanks for reporting that issue! I tried to run the same commands on my Windows 10 machine, but did not face this problem. Nevertheless, I removed some code that potentially caused this issue. Could you please update to v 1.2.4 and test if this problem persists?

**Comment by OndroV** [comment]
Thanks for fast fixing! It works now 👍
